export const shows = [
    {
        id: 1,
        title: 'The Good Doctor',
        summary: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur id tortor 
                et sapien auctor tristique sit amet quis quam. Sed vitae congue justo, vitae 
                fringilla sem. Praesent aliquet maximus consectetur. Proin et finibus eros. 
                Aenean eu tellus quam. Etiam eget elit odio. Vestibulum molestie semper mi, 
                quis dictum ligula consectetur nec.`,
        premiereDate: '2015-05-02',
        rating: 4,
        seasons: [
            {
                id: 1,
                title: "Season 1",
                summary: "",
                episodes: [
                    {
                        id: 1,
                        name: 'Episode 1',
                        title: "Before the Good 1",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 2,
                        name: 'Episode 2',
                        title: "Before the Good 2",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 3,
                        name: 'Episode 3',
                        title: "Before the Good 3",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 4,
                        name: 'Episode 4',
                        title: "Before the Good 4",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 5,
                        name: 'Episode 5',
                        title: "Before the Good 5",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                ]
            },
            {
                id: 2,
                title: "Season 2",
                summary: "",
                episodes: [
                    {
                        id: 1,
                        name: 'Episode 1',
                        title: "Before the Good 1",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 2,
                        name: 'Episode 2',
                        title: "Before the Good 2",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 3,
                        name: 'Episode 3',
                        title: "Before the Good 3",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 4,
                        name: 'Episode 4',
                        title: "Before the Good 4",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 5,
                        name: 'Episode 5',
                        title: "Before the Good 5",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                ]
            },
            {
                id: 3,
                title: "Season 3",
                summary: "",
                episodes: [
                    {
                        id: 1,
                        name: 'Episode 1',
                        title: "Before the Good 1",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 2,
                        name: 'Episode 2',
                        title: "Before the Good 2",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 3,
                        name: 'Episode 3',
                        title: "Before the Good 3",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 4,
                        name: 'Episode 4',
                        title: "Before the Good 4",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 5,
                        name: 'Episode 5',
                        title: "Before the Good 5",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                ]
            },
            {
                id: 4,
                title: "Season 4",
                summary: "",
                episodes: [
                    {
                        id: 1,
                        name: 'Episode 1',
                        title: "Before the Good 1",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 2,
                        name: 'Episode 2',
                        title: "Before the Good 2",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 3,
                        name: 'Episode 3',
                        title: "Before the Good 3",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 4,
                        name: 'Episode 4',
                        title: "Before the Good 4",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 5,
                        name: 'Episode 5',
                        title: "Before the Good 5",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                ]
            },
        ]
    },
    {
        id: 2,
        title: 'The Good Lawyer',
        summary: "",
        premiereDate: '2011-03-27',
        rating: 5.7,
        seasons: [
            {
                id: 1,
                title: "Season 1",
                summary: "",
                episodes: [
                    {
                        id: 1,
                        name: 'Episode 1',
                        title: "Before the Good 1",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 2,
                        name: 'Episode 2',
                        title: "Before the Good 2",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 3,
                        name: 'Episode 3',
                        title: "Before the Good 3",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 4,
                        name: 'Episode 4',
                        title: "Before the Good 4",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 5,
                        name: 'Episode 5',
                        title: "Before the Good 5",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                ]
            },
            {
                id: 2,
                title: "Season 2",
                summary: "",
                episodes: [
                    {
                        id: 1,
                        name: 'Episode 1',
                        title: "Before the Good 1",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 2,
                        name: 'Episode 2',
                        title: "Before the Good 2",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 3,
                        name: 'Episode 3',
                        title: "Before the Good 3",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 4,
                        name: 'Episode 4',
                        title: "Before the Good 4",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 5,
                        name: 'Episode 5',
                        title: "Before the Good 5",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                ]
            },
            {
                id: 3,
                title: "Season 3",
                summary: "",
                episodes: [
                    {
                        id: 1,
                        name: 'Episode 1',
                        title: "Before the Good 1",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 2,
                        name: 'Episode 2',
                        title: "Before the Good 2",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 3,
                        name: 'Episode 3',
                        title: "Before the Good 3",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 4,
                        name: 'Episode 4',
                        title: "Before the Good 4",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 5,
                        name: 'Episode 5',
                        title: "Before the Good 5",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                ]
            },
            {
                id: 4,
                title: "Season 4",
                summary: "",
                episodes: [
                    {
                        id: 1,
                        name: 'Episode 1',
                        title: "Before the Good 1",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 2,
                        name: 'Episode 2',
                        title: "Before the Good 2",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 3,
                        name: 'Episode 3',
                        title: "Before the Good 3",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 4,
                        name: 'Episode 4',
                        title: "Before the Good 4",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 5,
                        name: 'Episode 5',
                        title: "Before the Good 5",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                ]
            },
        ]
    },
    {
        id: 3,
        title: 'The Good Preacher',
        summary: "",
        premiereDate: '2019-08-11',
        rating: 8.4,
        seasons: [
            {
                id: 1,
                title: "Season 1",
                summary: "",
                episodes: [
                    {
                        id: 1,
                        name: 'Episode 1',
                        title: "Before the Good 1",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 2,
                        name: 'Episode 2',
                        title: "Before the Good 2",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 3,
                        name: 'Episode 3',
                        title: "Before the Good 3",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 4,
                        name: 'Episode 4',
                        title: "Before the Good 4",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 5,
                        name: 'Episode 5',
                        title: "Before the Good 5",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                ]
            },
            {
                id: 2,
                title: "Season 2",
                summary: "",
                episodes: [
                    {
                        id: 1,
                        name: 'Episode 1',
                        title: "Before the Good 1",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 2,
                        name: 'Episode 2',
                        title: "Before the Good 2",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 3,
                        name: 'Episode 3',
                        title: "Before the Good 3",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 4,
                        name: 'Episode 4',
                        title: "Before the Good 4",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 5,
                        name: 'Episode 5',
                        title: "Before the Good 5",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                ]
            },
            {
                id: 3,
                title: "Season 3",
                summary: "",
                episodes: [
                    {
                        id: 1,
                        name: 'Episode 1',
                        title: "Before the Good 1",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 2,
                        name: 'Episode 2',
                        title: "Before the Good 2",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 3,
                        name: 'Episode 3',
                        title: "Before the Good 3",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 4,
                        name: 'Episode 4',
                        title: "Before the Good 4",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 5,
                        name: 'Episode 5',
                        title: "Before the Good 5",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                ]
            },
            {
                id: 4,
                title: "Season 4",
                summary: "",
                episodes: [
                    {
                        id: 1,
                        name: 'Episode 1',
                        title: "Before the Good 1",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 2,
                        name: 'Episode 2',
                        title: "Before the Good 2",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 3,
                        name: 'Episode 3',
                        title: "Before the Good 3",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 4,
                        name: 'Episode 4',
                        title: "Before the Good 4",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                    {
                        id: 5,
                        name: 'Episode 5',
                        title: "Before the Good 5",
                        summary: "",
                        duration: 4500,
                        photo: "",
                    },
                ]
            },
        ]
    },
]
